name: Elixir CI

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  checks: write

env:
  MIX_ENV: test
  OTP_VERSION_SPEC: "26.2.3"
  ELIXIR_VERSION_SPEC: "1.16.2"
  CACHE_KEY:
  CACHE_RESTORE_KEY:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Environment
      run: |
        echo "CACHE_KEY=${{ runner.os }}-${{ env.OTP_VERSION_SPEC }}-${{ env.ELIXIR_VERSION_SPEC }}-${{ hashFiles('mix.lock') }}" >> $GITHUB_ENV
        echo "CACHE_RESTORE_KEY=${{ runner.os }}-${{ env.OTP_VERSION_SPEC }}-${{ env.ELIXIR_VERSION_SPEC }}-" >> $GITHUB_ENV

    - name: Elixir
      uses: erlef/setup-beam@v1.17.5
      id: setup
      with:
        otp-version: ${{ env.OTP_VERSION_SPEC }}
        elixir-version: ${{ env.ELIXIR_VERSION_SPEC }}

    - name: Restore Cache
      uses: actions/cache/restore@v3
      id: cache
      with:
        path: |
          deps
          _build
        key: ${{ env.CACHE_KEY }}
        restore-keys: ${{ env.CACHE_RESTORE_KEY }}

    - name: Install Mix Dependencies
      run: mix deps.get

    - name: Compile
      run: mix compile

    - name: Check Formatting
      run: mix format --check-formatted

    - name: Run Credo
      run: mix credo --strict

    - name: Run Tests
      run: mix test --cover

    - name: Code Coverage
      uses: peek-travel/coverage-reporter@v3
      if: github.event_name == 'pull_request'
      with:
        lcov_path: cover/lcov.info
        coverage_threshold: 90

    - name: Create PLTs
      run: MIX_ENV=dev mix dialyzer --plt

    - name: Run dialyzer
      run: MIX_ENV=dev mix dialyzer --format github

    - name: Save Build Cache
      uses: actions/cache/save@v4
      with:
        path: |
          deps
          _build
        key: ${{ env.CACHE_KEY }}
